version: "3"
services:
    docker-langserver:
        image: rcjsuen/docker-langserver
        container_name: docker-langserver
        volumes:
            - ./:/root/project_root
        stdin_open: true
        entrypoint: /bin/ash

    main:
        build:
            context: ./dockerfiles/neovim
            args:
                cmds: "docker-langserver:/docker-langserver/bin/docker-langserver"
        depends_on:
            - docker-langserver
        volumes:
            - ./:/root/project_root
            - /var/run/docker.sock:/var/run/docker.sock
            - ./coc-settings.json:/root/.config/nvim/coc-settings.json
        stdin_open: true
        working_dir: /root/project_root
